llm:
  model: "qwen3.5-122b"
  api: http://cci-siscluster1.charlotte.edu:8080/api/chat/completions
  api_key: "sk-06efd544e4234558abca35ec94c88085"
  system_message: "You are a helpful assistant."
  temperature: 0.7
  top_p: 0.9

tts:
  use_gpu: false
  model_name: 'tts_models/multilingual/multi-dataset/xtts_v2'
  speaker: 'Rosemary Okafor'
  language: 'en'

  deepspeed_enabled: False # default is True, will check for installed library

  streaming_enabled: False # default is False
  streaming_chunk_size: 60 # quick debug: 20
  streaming_overlap_wav_len: 4096

  # works best with streaming, although quality is as expected from real-time
  # sample_of_cloned_voice_wav: 'voice_to_clone.wav'
